# Generated by Django 5.0.2 on 2024-02-21 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('features', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('driverlicense_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('rent_duration', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.car')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='CarRent',
            field=models.ManyToManyField(through='polls.CarRent', to='polls.customer'),
        ),
    ]
